version: '3'

### Services
services:
### Web Server Container ##################################
    web:
        image: lobsterk/docker-nginx-php-fpm7.0
        container_name: wp-basic-web
        restart: always
        links:
           - "mysql"
        ports:
            - "8000:80"
        volumes:
           - ./www:/var/www
           - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
           - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
           - ./.docker/php-fpm/php.ini:/etc/php/7.2/fpm/php.ini
           - ./.docker/php-fpm/php-fpm.conf:/etc/php/7.2/fpm/php-fpm.conf
        networks:
           - wpnet

## MySQL Container
    mysql:
        image: mysql:5.7
        container_name: wp-basic-mysql
        restart: always
        ports:
            - "3306:3306"
        volumes:
              - ./mysql/:/docker-entrypoint-initdb.d/
              - ./.docker/mysql/:/etc/mysql/conf.d/
        environment:
            MYSQL_DATABASE: wp-basic-wpdb
            MYSQL_USER: wpuser
            MYSQL_PASSWORD: AJF7f@8fA
            MYSQL_ROOT_PASSWORD: K_%*Kg"<Sf
        networks:
            - wpnet

    # Adminer container
    adminer:
        image: adminer
        container_name: wp-basic-adminer
        links:
            - "mysql"
        ports:
            - "8080:8080"
        networks:
            - wpnet
networks:
    wpnet:

